abahmed/Deer

- src/CMakeLists.txt
- src/deer.cpp
- src/deer.h
- src/gui.cpp
- src/gui.h
- src/ui/main-window.ui
Fixes # .
- create gui class to manage the window
- create instance of gui class in deer_app
> Issue #5: Empty window using GTK3.

- AUTHORS.md
- resources/ui/main-window.ui
Fixes #9 
- Added a property in `resources/ui/main-window.ui` which sets the window position to center.
> Issue #9: Center start position added

- resources/ui/main-window.ui
- src/gui.cpp
- src/gui.h
Fixes #12  .
- menubar added with an exit button and dummy about button.
> Issue #12: Add simple menu

- src/gui.cpp
- src/gui.h
Issue #10
- Add deer gui class method to create pixbuf from file
- Set application icon to Deer-64.png
> Issue#10: Add application logo

- CONTRIBUTING.md
Updated CONTRIBUTING.md to reflect new develop to master promotion strategy.
Fixes # .
-
-
-
> Update CONTRIBUTING.md (#32)

- .eslintignore
- .eslintrc
- .gitignore
- .travis.yml
- __tests__/App-test.jsx
- app/App.jsx
- package.json
Fixes #29 
- Add eslint to scripts 
- make eslint a part of the CI process
- Fix typos in gitignore
> Fixes #29 Add eslint to scripts and make it a part of the CI process

- .editorconfig
Fixes #35 
- Add editorconfig file so that files created/used on windows uses LF to pass the lint checks.
> Add editorconfig to fix end-of-line problems

- .travis.yml
> Support MacOS in CI process

- README.md
- appveyor.yml
Fixes # 40
- Support Windows in CI process
- Add Appveyor badge in README.md
- Update Travis badge (refer to develop branch)
> Support Windows in CI process

- main.js
Fixes #18 .
- Changed  resolution to width: 720, height: 400
> Change browser resolution

- package.json
Fixes #60  .
- Added a precommit hook to avoid obvious failures that developers might overlook before committing.
> Added pre-commit hooks to enforce coding conventions

- app/components/note-list/note-list.jsx
- app/db/index.jsx
- app/middlewares/Notes.jsx
- app/reducers/NoteReducer.jsx
- app/store/index.jsx
Fixes #56  .
- Add PouchDB actions as middleware
- Implement add and read operations
- Integrate PouchDB operations with redux-store
> Added PouchDB support to persist notes

- package.json
Fixes #72 
- Update electron version
> Issue #72 : Update electron version

- main.js
- package.json
Fixes #78 
- Keep track of window state (height, width, position) and restore it while loading window
> Fixes #78 : Keep track of window state

- app/middlewares/Notes.jsx
- main.js
- package.json
- utils/logger.js
Fixes #80 
- Add logging library
- Add logging messages through project
> Fixes #80 : Add logging library

- AUTHORS.md
- app/actions/welcome.js
- app/components/Welcome.js
- app/containers/Welcome.js
Fixes # .
- Adding a new function to welcome actions 
- Call added function from Welcome component as it unmounts
> fix #84 adding function to clear out timer

- app/assets/styles/index.css
- app/components/Home.js
- app/components/HomeContent.js
Fixes #103 
- Implement HomeContent component
- Add default route to be loaded when Deer loads
> Fixes #103: Implement HomeContent component

- app/assets/styles/index.css
- app/components/NoteItem.js
- app/components/NoteList.js
Fixes #98 
- Implement NoteItem component
-
-
> Fixes #98: Implement NoteItem component

- README.md
- package.json
> Release v0.1.0

- app/actions/note.js
- app/reducers/note.js
Fixes #137
- Fixed the delete button (was deleting the whole note list instead of the selected note)
> Fixes #137: delete note now works as expected

- README.md
Fixes #142 
- Fix logo URL in README
> Fixes #142: Fix logo URL in README

- app/actions/header.js
- app/actions/modal.js
- app/actions/note.js
- app/actions/welcome.js
- app/components/Welcome.js
- app/db.js
- app/reducers/note.js
- app/reducers/welcome.js
- docs/Building-and-Installing.md
- main.js
Fixes NO-ISSUE
- Fix a typo
- Improves comments
> Fix a typo and improve comments

- AUTHORS.md
- docs/CONTRIBUTING.md
Fixes #158 
- Fixes links in `CONTRIBUTING.md`
- Update contributors
-
> Fix links in CONTRIBUTING.md

- app/components/YesNoModal.js
- assets/locales/en/yesNoModal.json
Fixes #164 
- Adding function to call proper strings in the modal
- Now the modal will support multi-language support
> Fix yesNoModal that was not translating buttons

- README.md
Fixes #170 
- Added three screenshots to README.
> Added screenshots in README

- README.md
Hi @abahmed. Kindly look into the update I have made...let me know if there's any changes I have ignored. Else, kindly, merge my request.
Details of change made is below:
./assets/images/Deer-256.png to
https://github.com/abahmed/Deer/blob/develop/assets/images/Deer-256.png
Fixes # .
-
-
-
> Issue #172 resolved. Updated Deer logo link from

- README.md
- app/constants/i18n.js
- assets/locales/pl/header.json
- assets/locales/pl/homeContent.json
- assets/locales/pl/index.js
- assets/locales/pl/noteEditor.json
- assets/locales/pl/settings.json
- assets/locales/pl/statusModal.json
- assets/locales/pl/yesNoModal.json
- utils/i18n.js
Fixes #204 .
- Added support for Polish
> Added support for Polish

- deploy.js
Fixes #223 
- update deploy script according to changes in API
> Fixes #223: update deploy script

- README.md
- app/constants/i18n.js
- assets/locales/cs/header.json
- assets/locales/cs/homeContent.json
- assets/locales/cs/index.js
- assets/locales/cs/noteEditor.json
- assets/locales/cs/settings.json
- assets/locales/cs/statusModal.json
- assets/locales/cs/yesNoModal.json
- utils/i18n.js
- Added Czech language support
> Added Czech language support

- .travis.yml
- deploy.js
Fixes #233 
- update deploy script according to the new API
> fix deployment error

- app/components/noteList/noteList.jsx
- docs/List-of-dependencies.md
- package-lock.json
- package.json
Fixes #235 
- Animate note list reordering
> Animate note list reordering

- app/components/noteList/noteList.jsx
- app/components/noteListItem/noteListItem.jsx
- app/entry.jsx
- docs/api.md
- package-lock.json
- package.json
Fixes #237 
- Add modification date in noteItem and used moment js to format it
> Add modification date in noteItem

- deploy.js
> fix deploy

- app/i18n/locales/de_du/about.json
- app/i18n/locales/de_du/dashboard.json
- app/i18n/locales/de_du/header.json
- app/i18n/locales/de_du/homeContent.json
- app/i18n/locales/de_du/index.js
- app/i18n/locales/de_du/noteEditor.json
- app/i18n/locales/de_du/settings.json
- app/i18n/locales/de_du/statusModal.json
- app/i18n/locales/de_du/yesNoModal.json
- app/i18n/locales/de_sie/about.json
- app/i18n/locales/de_sie/dashboard.json
- app/i18n/locales/de_sie/header.json
- app/i18n/locales/de_sie/homeContent.json
- app/i18n/locales/de_sie/index.js
- app/i18n/locales/de_sie/noteEditor.json
- app/i18n/locales/de_sie/settings.json
- app/i18n/locales/de_sie/statusModal.json
- app/i18n/locales/de_sie/yesNoModal.json
- app/i18n/locales/index.js
- added support for the german language
- you can decide if you prefer (du) or (sie)
> Added german language support

- README.md
- app/components/welcome/langList.js
- app/i18n/locales/index.js
- app/i18n/locales/tr/about.json
- app/i18n/locales/tr/dashboard.json
- app/i18n/locales/tr/index.js
- app/i18n/locales/tr/noteEditor.json
- app/i18n/locales/tr/settings.json
Fixes #251   .
- Added Turkish language support.
> Issue #251: Support Turkish language.

- .babelrc
- .editorconfig
- .eslintrc
- .prettierrc
- .vscode/extensions.json
- app/assets/theme.js
- app/components/about/about.jsx
- app/components/dashboard/dashboard.jsx
- app/components/home/home.jsx
- app/components/noteEditor/noteEditor.jsx
- app/components/noteList/noteList.jsx
- app/components/noteListItem/noteListItem.jsx
- app/components/notesPanel/notesPanel.jsx
- app/components/popoverIcon/popoverIcon.jsx
- app/components/settings/settings.jsx
- app/components/welcome/welcome.jsx
- app/entry.jsx
- app/middlewares/waitService.js
- app/utils/db.js
- package-lock.json
- package.json
Fixes #255 .
- Added eslint configurations in  .eslintrc file 
- Added prettier configurations in .prettierrc file
- Added eslint and prettier configurations in package.json
- Updated editor configurations in .editorconfig file
- Added recommended vscode plugins in .vscode/extensions.json
> resolves: #255 Added eslint and prettier config.
